-- Plan 3b-2: seed lineup_entries from docs/ingest/lineup.json.
-- Generated by scripts/generate-lineup-seed.ts. Re-run to regenerate.
-- start_at/end_at left NULL; admins fill via /admin/lineup.
insert into public.lineup_entries
  (artist_name, day, stage, ec_tags, genres, sort_order)
values
  ('Teddy Swims', 'Friday', 'Main Stage', '{"soul","r-and-b"}', '{"soul"}', 10),
  ('LP', 'Friday', 'Main Stage', '{"pop","singer-songwriter"}', '{"pop"}', 20),
  ('Subtronics', 'Friday', 'Hangar Stage', '{"dubstep","heavy-bass"}', '{"electronic"}', 30),
  ('Sub Focus', 'Friday', 'Hangar Stage', '{"dnb","high-energy"}', '{"electronic"}', 40),
  ('Ben Böhmer', 'Friday', 'Booha Stage', '{"melodic-house","dream-pop"}', '{"electronic"}', 50),
  ('Robin Schulz', 'Friday', 'Beach Stage', '{"dance-pop","summer"}', '{"electronic","pop"}', 60),
  ('The Cure', 'Saturday', 'Main Stage', '{"alternative-rock","post-punk"}', '{"rock"}', 10),
  ('Glass Animals', 'Saturday', 'Main Stage', '{"alt-pop","dream-pop","mainstream"}', '{"pop","alternative"}', 20),
  ('Massive Attack', 'Saturday', 'Main Stage', '{"trip-hop","atmospheric"}', '{"electronic","rock"}', 30),
  ('Justin Timberlake', 'Saturday', 'Main Stage', '{"pop","mainstream"}', '{"pop"}', 40),
  ('Mochakk', 'Saturday', 'Hangar Stage', '{"house","tech-house"}', '{"electronic"}', 50),
  ('Fred again..', 'Saturday', 'Hangar Stage', '{"uk-electronic","emotional-dance"}', '{"electronic"}', 60),
  ('FKJ', 'Saturday', 'Booha Stage', '{"nu-jazz","downtempo"}', '{"electronic","jazz"}', 70),
  ('Yves Tumor', 'Saturday', 'Booha Stage', '{"experimental","alt-rock"}', '{"alternative"}', 80),
  ('Honey Dijon', 'Saturday', 'Beach Stage', '{"house","disco-house"}', '{"electronic"}', 90),
  ('Twenty One Pilots', 'Sunday', 'Main Stage', '{"alt-pop","mainstream"}', '{"pop","alternative"}', 10),
  ('Tame Impala', 'Sunday', 'Main Stage', '{"psych-rock","dream-pop"}', '{"rock","alternative"}', 20),
  ('Anyma', 'Sunday', 'Main Stage', '{"melodic-techno","mainstream"}', '{"electronic"}', 30),
  ('Bicep', 'Sunday', 'Hangar Stage', '{"electronic","melodic-techno"}', '{"electronic"}', 40),
  ('Charlotte de Witte', 'Sunday', 'Hangar Stage', '{"techno","peak-hour"}', '{"electronic"}', 50),
  ('Floating Points', 'Sunday', 'Booha Stage', '{"electronic","jazz-adjacent"}', '{"electronic"}', 60),
  ('Yaeji', 'Sunday', 'Booha Stage', '{"house","alt-pop"}', '{"electronic"}', 70),
  ('Caribou', 'Sunday', 'Beach Stage', '{"electronic","indie-dance"}', '{"electronic"}', 80),
  ('Disclosure', 'Sunday', 'Beach Stage', '{"uk-house","dance-pop"}', '{"electronic"}', 90)
on conflict (artist_name, day, stage) do nothing;
