/**
 * Generates the seed migration body from docs/ingest/lineup.json.
 * Run with: pnpm tsx scripts/generate-lineup-seed.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

type Row = {
  artist: string;
  day: "Friday" | "Saturday" | "Sunday";
  stage: string;
  ec_tags?: string[];
  genres?: string[];
};

function pgArray(items: string[] | undefined): string {
  if (!items || items.length === 0) return "'{}'";
  const escaped = items.map(s => s.replace(/"/g, '\\"'));
  return `'{${escaped.map(s => `"${s}"`).join(",")}}'`;
}

function quote(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}

function main() {
  const jsonPath = resolve(__dirname, "../docs/ingest/lineup.json");
  const data = JSON.parse(readFileSync(jsonPath, "utf8")) as Row[];

  const lines: string[] = [];
  lines.push("-- Plan 3b-2: seed lineup_entries from docs/ingest/lineup.json.");
  lines.push("-- Generated by scripts/generate-lineup-seed.ts. Re-run to regenerate.");
  lines.push("-- start_at/end_at left NULL; admins fill via /admin/lineup.");
  lines.push("insert into public.lineup_entries");
  lines.push("  (artist_name, day, stage, ec_tags, genres, sort_order)");
  lines.push("values");

  const sortByDay: Record<string, number> = { Friday: 0, Saturday: 0, Sunday: 0 };
  const valueLines = data.map((row) => {
    sortByDay[row.day] += 10;
    return `  (${quote(row.artist)}, ${quote(row.day)}, ${quote(row.stage)}, ${pgArray(row.ec_tags)}, ${pgArray(row.genres)}, ${sortByDay[row.day]})`;
  });
  lines.push(valueLines.join(",\n"));
  lines.push("on conflict (artist_name, day, stage) do nothing;");

  const out = lines.join("\n") + "\n";
  const outPath = resolve(__dirname, "../supabase/migrations/20260526000400_seed_lineup_entries.sql");
  writeFileSync(outPath, out);
  console.log(`Wrote ${data.length} rows to ${outPath}`);
}

main();
